CREATE DATABASE IF NOT EXISTS game_db;

USE game_db;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

-- 游戏记录表
CREATE TABLE IF NOT EXISTS game_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    game_type VARCHAR(50) NOT NULL,
    player1_id BIGINT UNSIGNED NOT NULL,
    player2_id BIGINT UNSIGNED NOT NULL,
    winner BIGINT UNSIGNED,
    moves TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (player1_id) REFERENCES users(id),
    FOREIGN KEY (player2_id) REFERENCES users(id),
    FOREIGN KEY (winner) REFERENCES users(id)
);

-- 游戏房间表
CREATE TABLE IF NOT EXISTS game_rooms (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    game_type VARCHAR(50) NOT NULL,
    room_code VARCHAR(6) NOT NULL UNIQUE,
    host_id BIGINT UNSIGNED NOT NULL,
    guest_id BIGINT UNSIGNED,
    status VARCHAR(20) NOT NULL DEFAULT 'waiting', -- waiting, playing, finished
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (host_id) REFERENCES users(id),
    FOREIGN KEY (guest_id) REFERENCES users(id)
); 